### ISSUE TITLE
Add Contributor

### ISSUE THREAD

**Issue by Hardik0307** [Hardik0307/File_Explorer#30]
Comment on Issue or Pull Request, asking @all-contributors to add a contributor:
```
@all-contributors please add <username> for <contributions>
```

[See Contributions type Here](https://allcontributors.org/docs/en/emoji-key)

**Comment by Hardik0307** [comment]
@all-contributors please add @Hardik0307 for doc

**Comment by Hardik0307** [comment]
@all-contributors please add @Hardik0307 for code

**Comment by Barad7987** [comment]
@all-contributors please add @Barad7987 for design

**Comment by Barad7987** [comment]
@all-contributors please add @Barad7987 for code

**Comment by HarshadChovatiya** [comment]
@all-contributors please add HarshadChovatiya for Code

**Comment by HarshadChovatiya** [comment]
@all-contributors please add HarshadChovatiya HarshadChovatiya for Design

**Comment by HarshadChovatiya** [comment]
@all-contributors please add HarshadChovatiya for Design

**Comment by Hardik0307** [comment]
@Barad7987 do it here properly see the example of mine

**Comment by Barad7987** [comment]
@all-contributors please add @Barad7987 for code

**Comment by Barad7987** [comment]
@all-contributors please add @Barad7987 for design

**Comment by Hardik0307** [comment]
@all-contributors please add @Barad7987 for code

**Comment by Hardik0307** [comment]
@all-contributors please add @Barad7987 for code

**Comment by Hardik0307** [comment]
@all-contributors please add @Barad7987 for code

**Comment by Hardik0307** [comment]
@all-contributors please add @Barad7987 for code

**Comment by Hardik0307** [comment]
@all-contributors please add @Barad7987 for code
