### ISSUE TITLE
Add Contibutors

### ISSUE THREAD

**Issue by Hardik0307** [Hardik0307/File_Explorer#39]
Comment on Issue or Pull Request, asking @all-contributors to add a contributor:

```
@all-contributors please add <username> for <contributions>
```

**Comment by Hardik0307** [comment]
@all-contributors please add @Hardik0307  for code

**Comment by Hardik0307** [comment]
@all-contributors please add @Hardik0307 for doc

**Comment by Barad7987** [comment]
@all-contributors please add @Barad7987 for design

**Comment by Barad7987** [comment]
@all-contributors please add @Barad7987 for code

**Comment by Hardik0307** [comment]
@all-contributors please add @HarshadChovatiya for code
